import type { DefaultTheme } from 'vitepress'

export const search: DefaultTheme.AlgoliaSearchOptions = {
  appId: 'B7RKYVGCMX',
  apiKey: '361dc932541df0dcb50b5d27c6db32d5',
  indexName: 'thevite-theojs',
  askAi: 'RLkkeF9bBFA3',
  insights: true,
  locales: {
    root: {
      placeholder: 'Search docs',
      translations: {
        button: {
          buttonText: 'Search docs',
          buttonAriaLabel: 'Search docs'
        },
        modal: {
          searchBox: {
            clearButtonTitle: 'Clear search criteria',
            clearButtonAriaLabel: 'Clear search criteria',
            closeButtonText: 'Close',
            closeButtonAriaLabel: 'Close',
            placeholderText: 'Search docs',
            placeholderTextAskAi: 'Ask AI:',
            placeholderTextAskAiStreaming: 'Answering...',
            searchInputLabel: 'Search',
            backToKeywordSearchButtonText: 'Back to keyword search',
            backToKeywordSearchButtonAriaLabel: 'Back to keyword search'
          },
          startScreen: {
            recentSearchesTitle: 'Search History',
            noRecentSearchesText: 'No search history',
            saveRecentSearchButtonTitle: 'Save to search history',
            removeRecentSearchButtonTitle: 'Remove from search history',
            favoriteSearchesTitle: 'Favorites',
            removeFavoriteSearchButtonTitle: 'Remove from favorites',
            recentConversationsTitle: 'Recent conversations',
            removeRecentConversationButtonTitle: 'Remove conversation from history'
          },
          errorScreen: {
            titleText: 'Unable to fetch results',
            helpText: 'You may need to check your network connection'
          },
          noResultsScreen: {
            noResultsText: 'No relevant results found',
            suggestedQueryText: 'You can try searching for',
            reportMissingResultsText: 'Do you think this query should have results?',
            reportMissingResultsLinkText: 'Click to give feedback'
          },
          resultsScreen: {
            askAiPlaceholder: 'Ask AI: '
          },
          askAiScreen: {
            disclaimerText: 'Answers are generated by AI and may not be accurate, please verify yourself.',
            relatedSourcesText: 'Related sources',
            thinkingText: 'Thinking...',
            copyButtonText: 'Copy',
            copyButtonCopiedText: 'Copied!',
            copyButtonTitle: 'Copy',
            likeButtonTitle: 'Like',
            dislikeButtonTitle: 'Dislike',
            thanksForFeedbackText: 'Thanks for your feedback!',
            preToolCallText: 'Searching...',
            duringToolCallText: 'Searching ',
            afterToolCallText: 'Searched'
          },
          footer: {
            selectText: 'Select',
            submitQuestionText: 'Submit question',
            selectKeyAriaLabel: 'Enter key',
            navigateText: 'Navigate',
            navigateUpKeyAriaLabel: 'Up arrow',
            navigateDownKeyAriaLabel: 'Down arrow',
            closeText: 'Close',
            backToSearchText: 'Back to search',
            closeKeyAriaLabel: 'Esc key',
            poweredByText: 'Search provider'
          }
        }
      }
    }
  }
}
