name: npm_bark

permissions:
  contents: read

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  send-downloads:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm add axios -w

      - name: Run TypeScript script
        env:
          BARK_KEY: ${{ secrets.BARK_KEY }}
        run: node script/npm_bark.ts
